#!/bin/sh
# Make sure deps are available and run a Cardboard command.

set -e

cd $(dirname "$0")/..

SCRIPT=$(basename "$0")

BUNDLE_ARGS="--quiet"
[ "cibuild" = "$SCRIPT" ] && BUNDLE_ARGS="$BUNDLE_ARGS --no-quiet"

bundle install $BUNDLE_ARGS

bundle exec cardboard bootstrap
exec bundle exec cardboard "$SCRIPT" "$@"
